#!/usr/bin/env bash
if [[ -z "$VIRTUAL_ENV" ]]; then
	echo "No VIRTUAL_ENV set"
else
	echo "VIRTUAL_ENV is set"
	echo $VIRTUAL_ENV
fi
$VIRTUAL_ENV/bin/python -m flaskstrap "$@"
#python3 -m flaskstrap "$@"
